### ISSUE TITLE
Broken tab loading animation

### ISSUE THREAD

**Issue by fmeyertoens** [muckSponge/MaterialFox#100]
![ff](https://user-images.githubusercontent.com/26410884/58195291-e8591880-7cc7-11e9-8757-af5ff9159e23.gif)
Win 10, Dark Theme

**Comment by muckSponge** [comment]
I haven't experienced this on any version of Firefox or OS that I've tested. What version of Firefox are you running? Does occur with the light theme as well?

**Comment by fmeyertoens** [comment]
![ff-light](https://user-images.githubusercontent.com/26410884/58235225-b0da8280-7d40-11e9-9e21-c9bd06b4d876.gif)
FF 67

**Comment by fmeyertoens** [comment]
Also when I open spinner-busy.svg or spinner-progress.svg in firefox there is no animation (whereas in chrome there is)

**Comment by fmeyertoens** [comment]
I noticed that the animations worked before 0bfba62c2d10a84b6b3fccac67adebfcdfd45258 and 276ff94e56499a03314f22718d036b3ca96ba0b8 respectively.
When I change the --radius back to `calc(2 * 3.1415926536 * 37.5%)` it seems to work again
![ff-change](https://user-images.githubusercontent.com/26410884/58239771-fbacc800-7d49-11e9-9650-f250fbe3be5d.gif)

**Comment by muckSponge** [comment]
Oops, I wasn't actually testing a recent enough version on my Windows 10 rig. Replicated the bug and have reverted the radius calculation. I recall changing this due to a bug in FF68 where it refused to correctly apply stroke-dasharray from a variable with a percentage unit. I tested 68 on Windows 10 to be sure and it's working fine so not sure what happened there. May be a macOS-only bug (haven't tested it yet) or perhaps various refactors or a Nightly update fixed it.

**Comment by fmeyertoens** [comment]
LGTM
