### ISSUE TITLE
Firefox 67 w/ browser.urlbar.quantumbar pref enabled has offset search dropdown

### ISSUE THREAD

**Issue by BynariStar** [muckSponge/MaterialFox#111]
EDIT: Actual issue is quoted below:

> I was on an outdated version. The current version is improved, however, the dropdown is offset to the right.

Original issue (which was resolved but leaving for historic purposes):

Mozilla plans to Eventually™ replace the current Awesome Bar with the Quantum Bar (you can follow progress [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1520800)). However, it seems to break the MaterialFox dropdown.

Disabled:
![image](https://user-images.githubusercontent.com/1224547/58901130-3b3fc080-8709-11e9-8956-7f146b5dc793.png)

Enabled:
![image](https://user-images.githubusercontent.com/1224547/58901250-79d57b00-8709-11e9-9df2-225e64e0ed08.png)

You can try it yourself by enabling `browser.urlbar.quantumbar` in about:config.

**Comment by muckSponge** [comment]
I've tested that pref on 67 and 69 (macOS) and neither seem to have this issue. Are you sure you're on the most recent version? I did some work on this for #103.

**Comment by BynariStar** [comment]
I was on an outdated version. The current version is improved, however, the dropdown is offset to the right.

**Comment by muckSponge** [comment]
Annoyingly it varies. Sometimes it is aligned perfectly, sometimes it isn't. I've checked the vanilla theme and can see that the code they use to offset the dropdown contents to be in line with the urlbar doesn't work all the time and this code (actually in the form of two CSS variables) is all I have to use to try to align it in MaterialFox.

I can see Firefox 67 with the Quantum Bar pref enabled is slightly offset to the right, but it isn't under Nightly so if I tried to fix 67, I'd probably break Nightly (which has the pref enabled by default). Because Nightly is where the browser is headed, it's probably safest for me to leave it as-is but I'm happy to hear other suggestions.

**Comment by muckSponge** [comment]
I'll leave this open for suggestions for a day or two but if we can't work out a way to fix 67 w/ the pref without impacting Nightly, I'll have to mark as wontfix under the assumption that the issue doesn't affect most people (you have to manually enable that pref to be affected) and will be moot by the time 69 is stable.
