### ISSUE TITLE
Context menu options shifted to the left

### ISSUE THREAD

**Issue by DevPre24** [muckSponge/MaterialFox#114]
Some options of the right click context menus are shifted to the left.

<details>
 <a href="https://imgur.com/a/ct761A9">Imgur Album</a>
<br>
  <summary>Click to expand (Images)</summary>
  <img src="https://i.imgur.com/My1cSZA.png">
  <img src="https://i.imgur.com/3tDcLJv.png">
</details>

OS: Arch Linux 
Firefox Version: 67.0-1
Material Fox version: latest (master)

**Comment by muckSponge** [comment]
I thought I resolved this in v0.2.4 (latest commit, master as of writing). Could you double-check that you're up to date? I've had a chance to test the fix on macOS but not Linux, though the fix was to move some code to a Windows-only `@media` selector so this should have fixed the issue on all non-Windows platforms.

**Comment by DevPre24** [comment]
> I thought I resolved this in v0.2.4 (latest commit, master as of writing). Could you double-check that you're up to date? I've had a chance to test the fix on macOS but not Linux, though the fix was to move some code to a Windows-only `@media` selector so this should have fixed the issue on all non-Windows platforms.

Thanks, this was fixed with the latest master. Closing this issue.
