### ISSUE TITLE
Downloads and popup panels font size too large

### ISSUE THREAD

**Issue by ashtonlance** [muckSponge/MaterialFox#117]
It's me again haha. Love the theme! But something I noticed a few days ago is the downloads popup font size is huge on my Mac. See screenshot

![Screen Shot 2019-06-07 at 9 21 17 AM](https://user-images.githubusercontent.com/13652692/59107084-df8e5680-8905-11e9-811b-0308623e3420.png)

**Comment by muckSponge** [comment]
Bigger is better though, right?!?!?

I based the dimensions on the [Material list spec](https://material.io/design/components/lists.html#types) (see two-line list) but I suppose it is a bit on the large side compared to everything else. If it were a pure Material website it would look fine but because it's part of the browser it's inconsistently sized compared to the rest of the UI.

It's 72px tall at the moment. I can shrink this down to say, 48px and reduce the font size to match.

**Comment by ashtonlance** [comment]
Ha! I think that'd be perfecto 👌

**Comment by muckSponge** [comment]
Decided to go ahead and adjust the layout code substantially - uses `flex` layout over `-moz-box` to make it easier to force element sizes and centre elements without hacking margins. Height is reduced to 48px, font size is reduced from 120% and 100% to 100% and 85%, and padding has been adjusted.

**Comment by ashtonlance** [comment]
Beautiful, it looks great. Thanks, @muckSponge !

**Comment by muckSponge** [comment]
No problem, thanks for your input!
