### ISSUE TITLE
Minimize, maximize and close are slightly off

### ISSUE THREAD

**Issue by matey1116** [muckSponge/MaterialFox#124]
Hi there,

I noticed that minimize, maximize and close are slightly off on Windows: 

![image](https://user-images.githubusercontent.com/28358569/60389651-6aa1dd00-9abd-11e9-80ee-374a227a81f8.png)

If the mouse is at the top-right corner of the screen, I am not able to close Firefox or if I am at the top of the screen over the minimize button the same happens - not being able to do the action.

**Comment by Excigma** [comment]
When the window is not maximized, all the buttons are at the top left 

(Windows 10)

**Comment by muckSponge** [comment]
This is just here to annoy you ;)

But seriously, it's likely a regression caused by me trying to replicate Chrome's titlebar button dimensions, which are basically the default OS dimensions. Firefox decided to go hella chunky instead. I'll make a note of this and try to fix it for non-drag space users.

**Comment by Excigma** [comment]
On my other machine it works perfect (drag space on)
![image](https://user-images.githubusercontent.com/30280397/60763929-997a0d80-a0d2-11e9-810f-f1b122508a7b.png)

**Comment by muckSponge** [comment]
Should be resolved. Will close within a day or two if no objections.

**Comment by Jacobax** [comment]
This problem occurs again. Firefox 74.0
