### ISSUE TITLE
Tabs unfocused appear darker

### ISSUE THREAD

**Issue by momoe** [muckSponge/MaterialFox#125]
![image](https://user-images.githubusercontent.com/19848666/60638126-fa9f9980-9dd1-11e9-8000-09c30cd038e8.png)
I'm wondering if this the unfocused tabs are supposed to be visible like this, and if there's a configuration to turn those transparent.

**Comment by fmeyertoens** [comment]
https://github.com/muckSponge/MaterialFox/blob/4af50262c9c0dabecbc1618e33ebeb713168cd2e/chrome/tabbar/tabbar.css#L452
This is the line that is causing this. Can't figure out how intentional that is. It seems the darker background is/was? supposed to be applied to the arrow buttons on either side.

**Comment by momoe** [comment]
Thank you for this, Yes that corrected the problem by setting it to `	background-color: rgba(0, 0, 0, .0) !important;
`

As for the arrow buttons. I personally like having them visible and the one side is the end of the tabs open so it'd be slightly more transparent with firefox's effect.

**Comment by muckSponge** [comment]
This was intentional. Basically, when tabs overflow they scroll. Typically you want some indication that the tabs can scroll and Mozilla uses separators for this (vertical lines). This doesn't fit neatly into the Material design language, mostly due to spacing problems. Usually I'd copy Chrome's behaviour but Chrome doesn't have scrollable tabs - they just keep shrinking.

I went with a slightly darker scroll area colour to a) let the user know the tabs have overflowed, b) show the user exactly what is in the scrollable area and what isn't, and c) because it's a bit more consistent with the Material design language, which prefers subtle brightness variation vs separators or lines (seen in Mozilla's Photon design language).
