### ISSUE TITLE
Website security color support

### ISSUE THREAD

**Issue by mnxn** [muckSponge/MaterialFox#14]
I noticed with the new release that the Lock to the left of the URL no longer changes colors based on the security. Is this intentional?

![image](https://user-images.githubusercontent.com/25037249/45197925-81b6cc00-b218-11e8-8f89-f023355cf582.png)
![image](https://user-images.githubusercontent.com/25037249/45197971-c0e51d00-b218-11e8-812f-1d080d6b7457.png)

**Comment by muckSponge** [comment]
This was intentional, intended to mirror the behaviour of Chrome.

<img width="600" alt="image" src="https://user-images.githubusercontent.com/5405629/45198960-c5f3ac00-b2ac-11e8-9dc7-4e32a3b5bd13.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/5405629/45198990-e7549800-b2ac-11e8-900a-a3ad5d136df6.png">

I can understand the desire to keep the ```identity-box``` colours but I'm also torn between the "Chrome way" and the "Firefox way". In an ideal world Firefox would provide a pref to toggle this behaviour but without that, it is difficult to justify making it optional because it would involve manually changing the CSS or renaming a CSS file.

I'll keep this issue open as an enhancement and I'm eager to hear everyone's opinion on this. In the meantime I'll see if I can come up with any alternative solutions.

**Comment by muckSponge** [comment]
Actually, I could leverage something like:
```css
@supports -moz-bool-pref("materialfox.monochrome_identity.enabled")
{
	/* apply Chrome-style identity colours here */
}
```
And that way I just need to tell users to add a pref if they want the Chrome behaviour, as part of the optional installation instructions.

Who knows, one day I might be able to make an add-on which can toggle this and other prefs to provide a better customisation experience...

**Comment by muckSponge** [comment]
Settled for a custom ````materialFox.disableIdentityColors``` pref. Instructions to add pref are in README. See 863ae6a945fcff3187b792f3dc6d5825e2636174.
