### ISSUE TITLE
suggestions submenu obstructs selection

### ISSUE THREAD

**Issue by momoe** [muckSponge/MaterialFox#146]
While typing in the field of a website forum, the suggestion menu of previous entries will pop below, obstructing half of the field area. Furthermore it's obstructing any ability to mouse over and select any of the typed text. 

I would suggest dropping it lower 8-16px
![image](https://user-images.githubusercontent.com/19848666/63737983-1efd7c80-c83d-11e9-8ae6-cbdb28276687.png)

**Comment by muckSponge** [comment]
It's a complicated issue because there's invisible padding around the menu to allow the use of a drop shadow (Firefox's menus, popups, and panels are handled differently to other elements and can't have visible overflow so the conventional `drop-shadow` doesn't work without applying it to a child and padding out the parent by the shadow radius). This invisible padding is blocking mouse events but I don't think `pointer-events: none` resolves the issue.

I can probably offset the menu so that it at least doesn't visually obstruct the text but there may still be problems due to it blocking point events in the drop-shadow area.

**Comment by BlackTurtle69** [comment]
this can obscure things. It would be great if it could at least be moved below dropdown box :3
