### ISSUE TITLE
Problems with certain buttons placed on the TabToolBar

### ISSUE THREAD

**Issue by A-Sparowe** [muckSponge/MaterialFox#202]
So getting the MaterialFox to work is a piece of cake. Coming from me that says A LOT considering I'm literally learning as I go. I was even able to figure out how to place the "Close Min Max" buttons on the left side along with changing their look as well.  For some reason, they didn't immediately change after the theme was applied. 

Now, where my actual problem(s) come in is after I apply the theme the "new tab" and "list all tabs" buttons don't want to get all snuggled up next to the row of tabs like they're supposed to do. 

![Sb0eL3AplC](https://user-images.githubusercontent.com/11279897/72479432-0a089200-37ba-11ea-920b-727acac7e718.png)

Hopefully, you can see where they are at the moment in the included picture I added. If you're wondering, I used a "flexible space" button to separate them from the options button I added on the end there. 

Now as far as adding buttons to the "tabs toolbar", it goes as it should. It's just getting these two buttons and only these two buttons to, "stick?" to the last opened tab like they normally would. Other than the "options" button I added there, I may or may not add another button or two next to it and I already tried it to make sure it works. 

I guess I might as well ask while I'm here, but you see that space to the right of the "options" button? Is it possible to get rid of that, or is it better just leave it there for a "grabbing area?"

**Comment by xXReDxSparoweXx** [comment]
Ok, I see what you mean by how it's "special".  It's literally the most difficult and fidgety button lol. First I removed all the buttons I had placed there using the "customize" button. Then I dragged the "show all tabs" button so that it snapped to the left side of my tabs toolbar right in between the "min-max-close" buttons. Then I tried to get the "new tab" button to snap and stay snapped to the right, or last open tab in the toolbar. It didn't want to listen, well at least I thought it didn't. While it won't let you place it there by default, meaning it literally shows the button itself being snapped and placed thereafter you drag it there and will only stay snapped on the right side of the tabs toolbar if its placed at the end of the toolbar next to the "options/settings" button that was displayed in my previous picture. What got it to _actually_ stay snapped next to the last tab itself was when it auto-snaps where it wants to go and that was right next to the "show all tabs" button. So I just said screw it and chose to accept my losses and move on. What's funny is after I closed the customize window the "new tab" button now stays put and shows up after the last tab. When I enter the customize window again it shows it on the left side next to the "show all tabs" button. 

![firefox_EtSqKPTHT1](https://user-images.githubusercontent.com/11279897/72582849-bd03e900-38a9-11ea-967b-a8baccee69a7.png)

Very confusing. What I don't get and maybe it's because of my very limited knowledge of coding and basically learning everything as I go, is the fact that now the "show all tabs" button longer shows up. While it's not something I actually use all the time, it does come in handy when the amount of open tabs I have is more than what my window can show.

**Comment by muckSponge** [comment]
The customise mode shows the toolbar new tab button. This is the button which appears when the tabs are overflowing and is the only new tab button you can drag around. When you close the customise tab, it hides that new tab button and shows the one always next to the last tab. If you open too many tabs, this one hides and the toolbar one shows up and is always wherever you dragged it to when customising.

Now, the show all tabs button is only meant to appear when you have too many tabs open (or when customising). I found it a bit weird that it was shown in your earlier screenshot because your tabs were not overflowing. No idea how that happened but I figured you had some custom CSS to force-hide it. If you open say, 20 tabs, you should find that the show all tabs button appears again.
