### ISSUE TITLE
3dot button missing?

### ISSUE THREAD

**Issue by privacyguy123** [muckSponge/MaterialFox#211]
**Sanity checks (must complete)**
- [X ] I have read and followed the installation instructions in the README
- [X ] I have not modified the userChrome.css file
- [X ] I have tested the latest release or commit on master

**Describe the bug**
The 3dot menu button in the top right corner is missing on FireFox 74 update.

**To Reproduce**
Update to FireFox 74.

**Screenshots**
![image](https://user-images.githubusercontent.com/50337995/76422025-78be3200-639c-11ea-9643-33780d67e17c.png)

**System info**
 - Windows 10
 - FireFox 74

**Comment by muckSponge** [comment]
I'm unable to reproduce this. Is it missing all of the time or just sometimes? For example, it should change to an arrow when an update is pending. There may be another edge case I've missed where it's meant to change to something else but doesn't.

**Comment by privacyguy123** [comment]
It seems to have pushed the 3 dot menu item off the side of the screen and into some invisible limbo on the next row - only visible at browser startup, really not sure how to explain this any further O.o

**Comment by fmeyertoens** [comment]
Do you see the 3-dot-button when you open the customization menu or without any extension buttons?

**Comment by muckSponge** [comment]
I've tried adding 14+ buttons to the nav bar and shrinking the window to its smallest possible width and it still behaves as expected. What happens when you use the customise menu; do the buttons reappear? You're the only one thus far to experience this issue so it might be beneficial if you try a fresh profile to see if it's a specific configuration issue.

**Comment by privacyguy123** [comment]
75 update fixed it.
