### ISSUE TITLE
[Bug] Tabs shaking when there's a lot of them opened

### ISSUE THREAD

**Issue by yacoalioi** [muckSponge/MaterialFox#218]
**Sanity checks (must complete)**
- [X] I have read and followed the installation instructions in the README
- [X] I have not modified the userChrome.css file
- [X] I have tested the latest release or commit on master

**Describe the bug**
When opening multiple tabs to the point that they need to shrink, they start shaking a lot. 

**To Reproduce**
1. Open multiple tabs.
4. See issue

**Video**
https://i.imgur.com/i3X31ho.gifv

**System info**
 - OS: Windows 10
 - Firefox version: 75.0

**Comment by Excigma** [comment]
![o7Ma0BuWQk](https://user-images.githubusercontent.com/30280397/79056769-cbe21800-7cad-11ea-971d-4840386eacae.gif)

![image](https://user-images.githubusercontent.com/30280397/79056773-d6041680-7cad-11ea-9f16-4a50982ab793.png)

Unable to reproduce

**Comment by fmeyertoens** [comment]
![ff-tabs-shaking](https://user-images.githubusercontent.com/26410884/79067000-75c8a100-7cbc-11ea-9b69-0b51d4b1f8b9.gif)
OS: Windows 10
I can confirm this behavior but only when I open the customization menu. The shaking is essentially the switching of the tabs into overflowing and out. Therefore I can only reproduce it between 6 and 21 tabs (including the customize Firefox tab). Below 6 the tabbar isn't full and above 21 the tabs overflow anyway.

**Comment by Zebrazilla** [comment]
I'm able to reproduce this whenever I move the New Tab button away from the default position. The tabs begin to "shake" as described.

Release: MaterialFox-76.2

**Comment by opimdev** [comment]
I'm also able to reproduce this on the latest release (MaterialFox-76.2):
![5-02e7e134587d](https://user-images.githubusercontent.com/56732227/82730640-aefb2480-9cf0-11ea-9ca7-8d77462820f2.gif)
For me, commenting out the 
```
#tabbrowser-tabs[overflow] .tabbrowser-tab[last-visible-tab]:not([pinned])
{
	margin-inline-end: 8px !important;
}
```
block in [tabbar.css here](https://github.com/muckSponge/MaterialFox/blob/d0c6c75070f6738235316ab039e79b73ae1deb49/chrome/tabbar/tabbar.css#L492) seems to fix the issue.

**Comment by CorentinCAM** [comment]
Had the same issue, @rojidev 's workaround worked like a charm

**Comment by KhushrajRathod** [comment]
https://github.com/muckSponge/MaterialFox/pull/242
@rojidev I'm not sure as to what exactly this code is intended for (i.e. What are the side effects of commenting it out), any ideas?

> ```
> #tabbrowser-tabs[overflow] .tabbrowser-tab[last-visible-tab]:not([pinned])
> {
> 	margin-inline-end: 8px !important;
> }
> ```

**Comment by rojidev** [comment]
@KhushrajRathod I had a quick look into it and that block simply adds a margin to the end of the visible tabs when they're overflowing:
![unknown](https://user-images.githubusercontent.com/56732227/89100047-832ca700-d3e3-11ea-84f1-4e20e979626c.jpg)
The top being with the block commented out, and the bottom with `margin-inline-end: 7px !important` instead of 8px. Interestingly changing it to 7px seems to be working fine for me, the tabs don't shake anymore.
Looking at the browser content toolbox, it seems like it's an issue with the tabs being marked and unmarked as 'overflowing' constantly when it's set to 8px (you might have to open this image fully to actually read it):
![ezgif-6-f01a9dc8e15f](https://user-images.githubusercontent.com/56732227/89100072-c2f38e80-d3e3-11ea-93d8-906181d6f414.gif)
The tabs element (#tabbrowser-tabs) has an "overflow" tag being set to true and unset, same with the arrowscrollbox element (#tabbrowser-arrowscrollbox). The last tab has the 
```
#tabbrowser-tabs[overflow] .tabbrowser-tab[last-visible-tab]:not([pinned])
{
	margin-inline-end: 8px !important;
}
```
style being constantly added and removed. Not entirely sure of the actual root cause, but changing it to 7px instead seems to work fine for me so that might be a better idea instead of commenting the block out completely.

**Comment by KhushrajRathod** [comment]
@rojidev Can confirm it works with 7px, I'll update the PR now
