### ISSUE TITLE
Opening customize menu with full tab bar makes tabs favicon-only

### ISSUE THREAD

**Issue by KhushrajRathod** [muckSponge/MaterialFox#243]
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release for my Firefox version, or commit on master/beta branch (beta is for Firefox Beta only)  
**Note that I'm using Firefox Developer Edition**

**Describe the bug**
First: Take changes from https://github.com/muckSponge/MaterialFox/pull/242 to stop tabs from shaking _(Issue is reproducible even without this)_
When the complete tab bar is filled (such that opening a new tab will make tabs smaller), opening the customize menu will remove titles and leave only favicons in all tabs until customize menu is closed and enough tabs are closed to have extra space in the tab bar

**To Reproduce**
1. Enable MaterialFox
2. Open enough tabs to fill the tab bar (such that the plus sign is at the extreme right of your window), or shrink your window size so that the existing tabs fill the tab bar
3. Open customize menu **---- [Issue]**
4. Close customize menu ---- Issue persists
5. Close enough tabs to have some extra space in the tab bar
6. Titles are visible again

**Screenshots**
(GIF)
![Screen Recording 2020-08-01 at 6 29 17 AM](https://user-images.githubusercontent.com/44947946/89090514-dde9e280-d392-11ea-9f64-4c88f92ecd00.gif)

**System info**
 - OS: macOS 10.15.6
 - Firefox version: 80.0b2

**Additional context**
Note that this issue isn't seen without opening the customize menu (by just opening tabs)

**Comment by muckSponge** [comment]
Well that's odd. I'm testing same OS, same Firefox version and can't reproduce the problem. Does it happen with a fresh profile?

**Comment by KhushrajRathod** [comment]
Can reproduce with a Fresh Profile. Note that the issue is only seen on tabs that have a favicon, tabs without favicons retain their text.

[Full video](https://youtu.be/fmE0os9Z2T4)

**Comment by KhushrajRathod** [comment]
Note 2: This will only happen if your tab bar is full, so make sure you open enough tabs to fill the tab bar completely.

**Comment by muckSponge** [comment]
Great, thanks for the video. It seems `materialFox.reduceTabOverflow` is causing the problem. The curvy bits on the tabs are causing the tab bar to overflow before they would normally (basically due to some negative margins to keep the tabs tightly packed and their curved bottom corners overlapping). `reduceTabOverflow` tries to prevent the tabs from overflowing as often by compacting the contents of the tabs a little bit and centering the favicon when the tab bar is full. This helps to bring the tabs out of overflow as well, otherwise they stay in overflow (with the scroll arrows) far too long. The downside of this is if the tab bar overflows when it doesn't need to (which is happening when you activate the customize menu), the tabs look funky because they're only meant to overflow when they are very small.

For now, I'd recommend setting reduceTabOverflow to false. I'll remove it from the README for now, not sure if I'll be able to add it back – it's a complicated problem because in recent version of Firefox the tabs just overflow for barely any reason at all if they have negative margins, but negative margins are a must to get those curved tabs.

**Comment by KhushrajRathod** [comment]
Okay, so I assume this is the behavior you were trying to replicate:
![Screen Recording 2020-08-02 at 10 40 07 AM](https://user-images.githubusercontent.com/44947946/89116055-22eb4300-d47f-11ea-8292-f491859f524e.gif)
(The GIF first shows Firefox, then chrome)

**Comment by KhushrajRathod** [comment]
Should I leave the issue open?

**Comment by muckSponge** [comment]
I originally did replicate that but received some backlash because many Firefox users like that the tabs overflow. I settled for a middle-ground where the tabs tried to mimic Chrome's behaviour but would still overflow eventually. Unfortunately Firefox is very finicky about when it overflows and this behaviour doesn't really work properly any more (as you've noticed).

I would close this issue and I might revisit that reduceTabOverflow option later. What's more likely is I'll overhaul the tab code to try to resolve the underlying overflow problems, but that's a separate issue.

**Comment by KhushrajRathod** [comment]
Alright, thanks. I think all my issues are solved for now, I'll reach out if I see more

**Comment by muckSponge** [comment]
No worries, thanks for the detailed reports, makes it much easier to resolve.
