### ISSUE TITLE
Icons have weird dot in the middle

### ISSUE THREAD

**Issue by ralphSQ** [muckSponge/MaterialFox#251]
Hi,

I'm using Firefox 79.0 (20200720193547), and I downloaded the theme for version 80 since I cant find 79. I tried using 76 too but the same thing happened.

There's a weird circle dot in the middle of the back, forward, reload, overflow menu, and the three dot menu.
Please see image.

![materialfox bug](https://user-images.githubusercontent.com/43546617/89848010-fee2dc80-dbb7-11ea-8182-6b8bba7e1673.png)

**Comment by muckSponge** [comment]
Please refer to the installation instructions. You need to copy the user.js file into your Firefox profile directory, which will adjust some configuration settings to allow the theme to run correctly. If you've done this and still have the same issue, go to about:config and set `svg.context-properties.content.enabled` to `true`. Let me know though, because the user.js file should accomplish the same thing.

v80 will work fine for Firefox 79 and is the one I'd recommend.

**Comment by ralphSQ** [comment]
I forgot to copy the user.js file. Thanks!!
