### ISSUE TITLE
Firefox Proton

### ISSUE THREAD

**Issue by JVariance** [muckSponge/MaterialFox#281]
Hi, I love the MaterialFox Theme. I fear that Firefox Proton could break it.

Will you update Material Fox after Firefox Proton redesign, if necessary?

**Comment by muckSponge** [comment]
If there's enough demand for it I will either update MaterialFox for the redesign or I will create a new MaterialFox. Each update tends to add more baggage due to redundant code from older Firefox versions and it can be a headache to maintain so if I need to make big changes I'll probably need to start again from a clean slate.

**Comment by Katy-Glabs** [comment]
Yes please update
