### ISSUE TITLE
Automatic theme change for MacOS Mojave Dark Mode

### ISSUE THREAD

**Issue by ohbother** [muckSponge/MaterialFox#32]
Firefox 62 introduces an automatic dark theme change when using MacOS Mojave in a system-wide dark mode. It doesn't appear that this is working with MaterialFox enabled?

**Comment by muckSponge** [comment]
Installing Mojave and will test it out probably after I've fixed #30 (which has a rather large commit in the works).

**Comment by muckSponge** [comment]
#30 is closed now. Colour changes are still in the windows-improvements branch only. This branch essentially makes MaterialFox compatible with lightweight themes, which is what Firefox uses to do the automatic dark theme in Mojave in dark mode. As far as I know there's no other way to do it, other than to let Firefox do its thang (because the theme is hard-coded into a style attribute). I'll close this issue and you should see the changes in master reasonably soon. Just got a few light colour theme compatibility changes to make before I merge, which could take a day or two.
