### ISSUE TITLE
System default Min/Max/Close buttons

### ISSUE THREAD

**Issue by Virkkunen** [muckSponge/MaterialFox#33]
Since I applied this theme, Firefox now doesn't use my system's min/max/close buttons
![image](https://user-images.githubusercontent.com/9111925/46101121-86302e00-c1a1-11e8-9d24-e6b34ca1e76e.png)
They don't even match the theme's color.

I'm on Windows 10 and I am using the Arc theme, and the buttons look like
![image](https://user-images.githubusercontent.com/9111925/46101171-a4962980-c1a1-11e8-98a6-915c408fbab2.png)
 
I've searched on reddit and a user said that it can be fixed by commenting out or deleting tags titlebar-min, titlebar-max and titlebar-close on the .css files, however, Material Fox doesn't seem to have any.

Is there anything that can solve this issue?

**Comment by muckSponge** [comment]
That's really odd. I don't have a custom theme installed to test at the moment but could you try:

1. Remove userChrome.css and restart Firefox
2. If the problem has gone, add userChrome.css back and
3. Remove _tabbar.css and restart Firefox and let me know what happens

I'm only modifying the titlebar buttons on macOS so not sure why your buttons would be affected. Doing the above will confirm that the problem is in my code and then I can look further into it.

**Comment by muckSponge** [comment]
Looks like it isn't a bug in this theme so I'll mark it as closed, but if you find a solution, just open another issue and I'll see if I can integrate it.
