### ISSUE TITLE
Helper issues

### ISSUE THREAD

**Issue by Madis0** [muckSponge/MaterialFox#45]
- In private mode, the dropdown doesn't work. Maybe a descriptive text or option (to use different colors or not) would be better?
- The listing home page and support site lead to [non-existing location](https://github.com/muckSponge/MaterialFox/tree/theme-compatibility)

**Comment by muckSponge** [comment]
Fixed the home page; was pointing to a branch I deleted.

Private browsing mode is a little bit tricky because MaterialFox enforces the dark theme via CSS, basically overriding any lightweight themes (this is to cater for people not using MaterialFox Helper). MaterialFox Helper on the other hand, also enables its own dark theme for private browsing mode, though this doesn't really take effect due to the CSS override. It was originally designed for the theme-compatibility branch which did not force a private browsing theme via CSS.

Possible fixes are:
- Remove the private browsing mode CSS from the userChrome theme and add an option to disable dark mode in private browsing, or
- Disable the button / theme selector when in private browsing mode

**Comment by Madis0** [comment]
>Remove the private browsing mode CSS from the userChrome theme and add an option to disable dark mode in private browsing

This would be the preferred solution IMO, the long-term goal should be to make this userStyle do as little as possible, while the Helper expands it's use as the Theming API improves. Otherwise you're just spending more time supporting both cases at once...

**Comment by muckSponge** [comment]
Yeah, you make a good point, although I just realised on Windows and Linux, activating a lightweight theme (such as the private browsing theme) causes it to theme the tab bar (ie, change its ```background-color```) which is not in line with Chrome's behaviour, where the tab bar retains the window colour. If I were to remove the custom private browsing CSS code, Windows 7 is probably going to look pretty funky.

**Comment by muckSponge** [comment]
MaterialFox Helper is redundant now because built in light and dark themes are specifically overridden with Material colours via CSS. This only applies to themes with the same accent_color as the built in themes, which is a very improbably occurrence, making this a relatively safe and compatible with just about all lightweight themes.

I did this so that I have just the one codebase to maintain (this theme) and it reduces the installation complexity (no more messing around with theme selection), and the biggest benefit of all, is that it works with macOS Mojave's dark mode. Firefox recently implemented support for it by forcing (via style attributes) the dark theme. This made it impossible to support automatic dark mode switching (it's not part of the extension API). The way around this was to check that style attribute for the default light or dark theme colours and if present, override the corresponding CSS variables to match the Material colour palette.

Untested on Windows 7 or Linux but I'm satisfied enough to close this issue.
