### ISSUE TITLE
Private window icon

### ISSUE THREAD

**Issue by Madis0** [muckSponge/MaterialFox#48]
...could emulate Chrome's Incognito mode. Not sure if you should only replace the Firefox one or also add a check for the Synced Tabs button though.

**Comment by Madis0** [comment]
Cool implementation, but I think it would make more sense to just change the icon of Synced Tabs when it's present in the toolbar (instead of removing and creating a new element), as user can move the button anywhere in Firefox.

**Comment by muckSponge** [comment]
I wanted to remove the private browsing icon from the tab bar and in order to do so, I needed to make sure the private browsing icon was always visible somewhere in private browsing mode. I settled on this implementation because as per Chrome's behaviour, the incognito icon replaces the profile icon. In Chrome, the profile icon is always present but in Firefox, someone can remove it altogether (and this is in fact the default state) so I force hide the profile icon, regardless of its location, and show the incognito icon next to the hamburger menu.

Perhaps a better way to accomplish this might be to check the toolbars for the ```sync-button``` and if present, change its icon and set ```pointer-events: none```, otherwise show the icon as a pseudo element like it is now. This way, if someone has gone to the trouble of putting the ```sync-button``` somewhere specific, it will remain there but show the incognito icon, and if they never added the ```sync-button```, add it for them next to the hamburger menu as per Chrome's behaviour.

Alternatively, I could force the ```sync-button``` to always be next to the hamburger menu if it is in the toolbar but this artificially limits the level of customisation Firefox users have come to expect, for the sake of consistency.

**Comment by Madis0** [comment]
> Perhaps a better way to accomplish this might be to check the toolbars for the sync-button and if present, change its icon and set pointer-events: none , otherwise show the icon as a pseudo element like it is now. This way, if someone has gone to the trouble of putting the sync-button somewhere specific, it will remain there but show the incognito icon, and if they never added the sync-button , add it for them next to the hamburger menu as per Chrome's behaviour.

Yup, that's what I was thinking about. But only if it doesn't introduce more XBL (only CSS), because that's [getting removed soon.](https://bgrins.github.io/xbl-analysis/)

**Comment by muckSponge** [comment]
Since Mozilla introduced the account button, I've replaced that icon with the incognito icon when in private browsing mode. To keep in line with Chrome's behaviour, the button shows a "Private" label. I can't replicate the menu itself so I've disabled the button.

Note, this isn't going to play nice with non-English locales due to the hard-coded label and I'm not willing to translate into every possible locale just yet so I only show the label for English locales.

See 5d9065e0749fcaf1fbc01785a2180130e5481347, f7edf56a4a98b3db236fe1818f8018ff85fa7a40.
