### ISSUE TITLE
No highlight when tabing through search suggestion

### ISSUE THREAD

**Issue by euh2** [muckSponge/MaterialFox#69]
When searching through adressbar, the selected search is not highlighted when using ```<Tab>```. Mouse hover shows selection though.
![no highlight color](https://media.giphy.com/media/2SYbYFBHEeuw7LZCeS/giphy.gif)

--
And the shadow below the pop-up looks not quiet right.

**Comment by muckSponge** [comment]
Good catch - I'll look into that. The shadow seems to be a graphics glitch which means I might need to look for an alternative method for producing the shadow. It's quite challenging because depending on the OS, the popups and menus are styled (and behave) very differently and on Windows and Linux require some rather creative solutions to get nice, big shadows.

**Comment by heubergen** [comment]
Same for arrows selection under macOS. I see the same issue with dropdown selects (https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select to try)

**Comment by muckSponge** [comment]
Yeah, your new issue should be fixed now too (in d7d471595dc60b5c8e6d6bd01827c4155ed9e56d).
