### ISSUE TITLE
Private browsing mode doesn't play nice with default theme

### ISSUE THREAD

**Issue by Eddi2015** [muckSponge/MaterialFox#83]
EDIT: Title was modified as per [this comment](https://github.com/muckSponge/MaterialFox/issues/83#issuecomment-498044598). This issue is not specifically related to Linux.

As the title says I have some issues. It might be possible that this is related to my GTK theme called "Adapta-Maia". It's the default theme on Manjaro Linux and I don't want to change it as it looks awesome. The problem is that the search bar and the context menus (including right click menu and three-dot-menu on the top right) are dark and the tabs and the bookmark bar are light. Here are some screens:
![DarkAdressBar](https://user-images.githubusercontent.com/36605424/54072987-9f252b00-4279-11e9-9721-5bf6f7f6a914.png)
![DarkLibrary](https://user-images.githubusercontent.com/36605424/54072988-9f252b00-4279-11e9-9805-00096bd8222d.png)
![WholeWindow](https://user-images.githubusercontent.com/36605424/54073008-deec1280-4279-11e9-9d7e-f1076d7130cb.png)

I am using the latest master branch and the default theme (not light and not dark; the default one).

**Comment by edoz90** [comment]
no problem per me with all themes (dark, default, light). My GTK theme is Numix-DarkBlue.

![Screenshot 2019-03-09 15:51:02](https://user-images.githubusercontent.com/6991986/54073072-3f338200-4283-11e9-9daf-0ead155b87ef.png)

![Screenshot 2019-03-09 15:51:25](https://user-images.githubusercontent.com/6991986/54073077-4bb7da80-4283-11e9-9388-76a7a28b1a40.png)

**Comment by muckSponge** [comment]
Quite odd that the menus and urlbar background are dark but rest of theme is light. Just curious, what does it look like without the theme applied,and does it look ok in light and dark themes (not default)?

**Comment by Eddi2015** [comment]
At the moment I can't disable or change my GTK theme as this would require logging out or rebooting the PC. The problem is that I'm downloading a big file atm, so I'll try changing the theme later. Anyway, here are some screenshots of the light (Hell) and dark (Dunkel) theme:
![DarkTheme](https://user-images.githubusercontent.com/36605424/54086697-ca744c80-4343-11e9-803a-b22c246a3be3.png)
![LightTheme](https://user-images.githubusercontent.com/36605424/54086698-cb0ce300-4343-11e9-9802-7491b18befc0.png)

As you can see, both are dark. Maybe you need to fix some variables, like elements that would be light normally and that you didn't override might need to be overridden (just an idea).

**Comment by muckSponge** [comment]
MaterialFox enforces its own "theme" by overriding the same CSS vars that a lightweight theme provides as a `[style]` attribute on the `:root` (`#main-window`) and a few other select elements. It only overrides the built-in themes and to do so it uses a very specific selector. For dark mode this is either during private browsing (`[privatebrowsingmode]`) or when the root has a style attribute containing `--lwt-accent-color:rgb(12, 12, 13);`, which is the general background colour provided by the dark mode theme. Likewise, for light mode, it looks for `--lwt-accent-color:rgb(227, 228, 230);`.

In the case of the urlbar, by default I force a light colour (`hsl(200, 12%, 95%)`), and override it with a dark colour (`hsl(206, 8%, 17%)`) if `:-moz-lwtheme-brighttext` or `[privatebrowsingmode]` is set on the root. You're not private browsing so that leaves `:-moz-lwtheme-brighttext`, which means the browser thinks it is using a lightweight theme with light text (and usually a dark background).

*But* nothing is that simple of course. I've got a `@media` selector for Ubuntu - and this probably is used for other Linux distros and themes - which sets the toolbar colour to whatever the system toolbar colour is and the text colour to whatever the system text colour is (all determined by the browser) when there is *no* lightweight theme applied (i.e., the default theme).

All I can really suggest at this point is to send a screenshot of what your browser looks like without MaterialFox, for the default, light, and dark themes, and this will give me an idea of which CSS selectors are active. From what I've seen so far, I'd expect the default theme to look dark and that's weird because the system colours seem to be the opposite, and usually the default theme is similar to the OS theme.

**Comment by muckSponge** [comment]
I installed Manjaro in a VM but its default theme was Breath and I can't seem to find Adapta-Maia. Regardless, I can see there are a few issues so I'll work on those when I have time and hope it resolves your problem.

**Comment by Eddi2015** [comment]
Ok, so I finally found the issue! It's not because of my theme (Adapta), but rather because I'm using a user.js file (https://github.com/pyllyukko/user.js/). It looks like my settings force Firefox to use the Private Browsing mode. Somehow this does not mean that firefox uses the dark theme, though. It looks like MaterialFox is confused and uses the light theme for some areas and for others the dark area. Is it possible for you to add an option to 'force' light mode regardless of using PrivateBrowsing mode or not? When I disable the Private Browsing mode my firefox doesn't connect to any sites somehow, so I have to keep these settings in order to be able to use Firefox, but I'd also like to use MaterialFox.

**Comment by Eddi2015** [comment]
![PrivateBrowsing](https://user-images.githubusercontent.com/36605424/58763544-798f8100-854b-11e9-9c62-a0f6695af11a.png)

**Comment by muckSponge** [comment]
This was partially an issue with the theme not going "full dark mode" when private browsing and using default or light theme. I've fixed this now.

I've also rearranged things so that only temporary private browsing mode (via new private browsing tab) will enforce dark mode. Always-on private browsing will use whatever theme you select.
