### ISSUE TITLE
Firefox Color support

### ISSUE THREAD

**Issue by Keith94** [muckSponge/MaterialFox#9]
Not sure if it makes sense to support [Firefox Color](https://color.firefox.com/), but I thought I'd raise the issue anyway; the issue being that some of the pre-selected themes don't play nice with this theme.

**Comment by muckSponge** [comment]
Looks like it wouldn't be possible to perfectly match the Chrome colours with Firefox Color. If you decode the URLs with [json-url](http://output.jsbin.com/cayuhox) you'll notice you can only change 7 colours (well, I guess you can infer that from the UI too), but with some carefully arranged CSS you could get 90% of the way there. It will no longer respect the dark colour scheme in private browsing mode so I'm hesitant to go any further right now.

**Comment by Keith94** [comment]
Sounds tricky! That's OK if it can't be helped. Just wanted to bring it to your attention. :)

**Comment by Keith94** [comment]
Cool! That seems promising indeed.

**Comment by muckSponge** [comment]
Could you try out [MaterialFox Helper](https://addons.mozilla.org/en-US/firefox/addon/materialfox-helper/) with the theme-compatibility branch and let me know how it goes? The theme should now be fully compatible with Firefox Color, regardless of whether you use the helper.

Due to the complex way in which themes can be installed (either via theme extensions or add-ons which directly modify the theme), it is quite difficult for the add-on to know exactly what theme is enabled so it might sometimes say a theme is enabled but in fact another add-on (like Firefox Color) is overriding it. This is evident if you select a theme in the MaterialFox Helper button, then open up Firefox Color and select a preset in there. The helper button isn't and can't be aware of the Firefox Color themes and will think you've still got the previous theme enabled. I'll make a few modifications later so it doesn't tell you a theme is enabled when it has actually been overridden.

**Comment by Keith94** [comment]
I will check it ASAP.

**Comment by muckSponge** [comment]
Thanks! One thing I neglected to think about is the fact that the add-on doesn't store any settings so the theme will reset after restarting the browser. Will hopefully have this fixed in the next version.

**Comment by muckSponge** [comment]
Added persistent storage and improved compatibility with Firefox Color. It's still not perfect because I don't have access to Firefox Color's theme data - only current theme. Got a few ideas to improve it. Until then, select Default as theme and then set your colours with Firefox Color. If you change the theme again through MaterialFox Helper, you'll need to go and redo you Firefox Color selection.

**Comment by muckSponge** [comment]
Interesting! Thanks for trying it out. Looks like I need to force the urlbar text colour to ensure it is either light or dark, and not leave it up to the theme to set it directly. Thought I was already doing this but must have missed something.

The way it worked on Chrome when I tested was it either picks the regular light urlbar or dark urlbar and themes aren't allowed to affect it other than telling it to be the light or dark variant, and this is what I'm aiming for.

**Comment by jcruzs** [comment]
I'm using vivaldifox for the moment and it seems to be working nice. I not sure how the extensions apply the colors but is working great in case you want an extensions that adapt the color from the site you visit like vivaldi browser.

**Comment by muckSponge** [comment]
Should work even better with the windows-improvements branch. Just need to improve light theme compatibility.

**Comment by Keith94** [comment]
V2 has been released. https://www.ghacks.net/2018/10/03/style-firefox-with-firefox-color-version-2/

**Comment by muckSponge** [comment]
Thanks @Keith94. V2 should not affect compatibility, just adds more customisation. The thing MaterialFox doesn't let you specifically change is the URL at background and text colour, keeping in line with Chrome.

**Comment by muckSponge** [comment]
Haven't done anything to improve light theme compatibility but I think it's good enough to merge into master. Will mark this as closed now, all theme compatibility changes are in master.
